name: Install dependencies

runs:
  using: composite
  steps:
      - name: Install apt dependencies and upgrade pip
        shell: bash -el {0}
        run: |
          apt-get update && apt-get install -y libgl1-mesa-glx libxrender1 xvfb
          python3 -m pip install -U pip